### ISSUE TITLE
Remove WOIS prefix

### ISSUE THREAD

**Issue by ctottrup** [DHI-GRAS/qgis-processing-workflow#11]
When creating new workflows they all feature with a WOIS prefix, which should be removed:
![capture](https://user-images.githubusercontent.com/6794617/35322728-300e02ce-00e3-11e8-9e6f-3306880a4e52.JPG)

**Comment by j08lue** [comment]
Good you raise this. I have looked through the repo already (https://github.com/DHI-GRAS/processing_workflow/search?utf8=%E2%9C%93&q=wois&type=) but there is nowhere the code mentions "WOIS", only the docstrings do.

@radosuav, do you have an idea where the logo and "WOIS Workflow" might come from?

**Comment by radosuav** [comment]
It's [here](https://github.com/DHI-GRAS/processing_workflow/blob/GW-A_dev/Workflow.py#L146).

It should be replaced by 
```python
self.provider.name
```

Then the string (and the icon) will come from the collection.conf file (see [WorkflowCollection class](https://github.com/DHI-GRAS/processing_workflow/blob/GW-A_dev/WorkflowCollection.py)).

**Comment by j08lue** [comment]
Thanks a bunch, @radosuav, I guess the GitHub search failed quite bad here...

I implemented that change in #12, so the window title for a new workflow went from

![image](https://user-images.githubusercontent.com/3404817/35332821-b3466108-010c-11e8-8813-777094d53f1f.png)

to

![image](https://user-images.githubusercontent.com/3404817/35332775-77c237e2-010c-11e8-9f4f-8227faddc305.png)

I don't know how logo and provider name are set in the case of WOIS or GWA or other providers. (What are providers, anyways?) But I will figure that out eventually. 😄 I guess this works fine, so I'll merge now.

**Comment by radosuav** [comment]
Providers provide algorithms ;) Basically each Processing provider has a set of algorithms under its own tree in the Processing Toolbox (PT) and sets up an interface between the algorithms' GUI visible in QGIS and the algorithm implementation in an outside software or library (e.g. GDAL or SNAP). 

Workflows are treated as algorithms by the PT, even though they are composed of other PT algorithms (similarly to Processing models). In order to allow for customization of the workflow libraries (e.g. WOIS Workflow library), the workflows can be grouped into collections. Each collection is just a directory with a bunch of workflow files and collections.conf file which holds information about the logo, name and description of the collection. When the Workflows plugin is initialized it goes through all the collection directories and sets each one of them up as a separate algorithm provider. That way the collections can have individual trees in the Processing Toolbox (with separate logos and names), can be switched on and off individually, etc.

For a bit of an overview of the Processing architecture have a look at [this paper](http://www.mdpi.com/2220-9964/4/4/2219/htm). In QGIS 3 some of the details might have changed but the overall architecture should be similar.

Hope that makes sense :)
